package com.botu.img.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.botu.img.bean.Newsbean;

import com.botu.img.dao.NewsbeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsbeanDaoConfig;

    private final NewsbeanDao newsbeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsbeanDaoConfig = daoConfigMap.get(NewsbeanDao.class).clone();
        newsbeanDaoConfig.initIdentityScope(type);

        newsbeanDao = new NewsbeanDao(newsbeanDaoConfig, this);

        registerDao(Newsbean.class, newsbeanDao);
    }
    
    public void clear() {
        newsbeanDaoConfig.clearIdentityScope();
    }

    public NewsbeanDao getNewsbeanDao() {
        return newsbeanDao;
    }

}
