package com.botu.img.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import com.botu.img.bean.Newsbean;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NEWSBEAN".
*/
public class NewsbeanDao extends AbstractDao<Newsbean, Long> {

    public static final String TABLENAME = "NEWSBEAN";

    /**
     * Properties of entity Newsbean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Tilte = new Property(1, String.class, "tilte", false, "TILTE");
        public final static Property Picurl = new Property(2, String.class, "picurl", false, "PICURL");
    }


    public NewsbeanDao(DaoConfig config) {
        super(config);
    }
    
    public NewsbeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NEWSBEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TILTE\" TEXT," + // 1: tilte
                "\"PICURL\" TEXT);"); // 2: picurl
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NEWSBEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Newsbean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String tilte = entity.getTilte();
        if (tilte != null) {
            stmt.bindString(2, tilte);
        }
 
        String picurl = entity.getPicurl();
        if (picurl != null) {
            stmt.bindString(3, picurl);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Newsbean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String tilte = entity.getTilte();
        if (tilte != null) {
            stmt.bindString(2, tilte);
        }
 
        String picurl = entity.getPicurl();
        if (picurl != null) {
            stmt.bindString(3, picurl);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Newsbean readEntity(Cursor cursor, int offset) {
        Newsbean entity = new Newsbean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // tilte
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // picurl
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Newsbean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTilte(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPicurl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Newsbean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Newsbean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Newsbean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
